[package]
name = "leben-chess-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
ggez = "0.9.3"
rsoderh_chess = { git = "https://github.com/INDA25PlusPlus/rsoderh-chess", rev = "f406bb6" }
clap = { version = "4.5.45", features = ["derive"] }
